name: env test

on:
  workflow_dispatch

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'Prod' || github.ref_name == 'qa' && 'Qa' || github.ref_name == 'dev' && 'Dev' }}
    steps:
      - name: "Say Hello"
        run: echo "secret ${{ secrets.sec_1 }}, variable ${{ vars.var_1 }}"
