name: env test

on:
  workflow_dispatch

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ['Dev', 'Qa', 'Prod']
    environment: ${{ matrix.target }}
    steps:
      - name: "Say Hello"
        run: echo "secret ${{ secrets.sec_1 }}, variable ${{ vars.var_1 }}"
