name: env test

on:
  workflow_dispatch

env:
  TARGET: Prod

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - name: "Say Hello"
        run: echo "secret ${{ secrets.sec_1 }}, variable ${{ vars.var_1 }}"
